[package]
name = "zkcamp_stealthdrop"
authors = ["Haythem Sellami"]
compiler_version = "0.7.1"
type = "bin"

[dependencies]
ecrecover = { tag = "v0.8.3", git = "https://github.com/haythemsellami/ecrecover-noir" }
array_helpers = { tag = "v0.1.2", git = "https://github.com/haythemsellami/noir-array-helpers" }